language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- 3.7-dev
install:
- pip install -r requirements.txt
- pip install pytest
script:
- py.test test.py
stages:
- test
- quality
- deploy
jobs:
  include:
  - stage: quality
    python: 3.6
    install:
    - pip install -r requirements.txt
    - pip install pytest flake8 coveralls codacy-coverage
    script:
    - coverage run --source=junitparser test.py
    - coverage xml
    - coveralls
    - python-codacy-coverage -r coverage.xml
  - stage: deploy
    python: 3.6
    deploy:
      provider: pypi
      user: gastlygem
      password:
        secure: "A2wUv7d3+W7+b5+SabMYfc4DFH0RbrLLjtFVQ+wHy+Us5SDDXWmRWfKo273Sta0XuMm9W6Vt3fMosYha8MjbiWsfur4tcPGynJoGrbfPZ3QtIkKKdnDRVckS1KEv07hmP/QXDk5codvyO2IG3u+Lc0QkUfN190BJ89H7Qhy38Erdjq8pDHAItuOSw+N4+u++ybjyLxnBUOl8XVRnIMZ1RMmSMH+hiDk16oz1TCHGs423N6jztRzNQsglV4UaGY60KwV+0Evu9TMxiGkM/f3YEZR0yqz8BA0eDqomnx9j8RBr0LUo2MXbPFBv7kQCyhcieeN4HSg9rsrf3gGaCTivOEB39DPLeaWg1hcQKdBWHc2G+aNzcLMg0J/k8g9tdWg5csMnCwAdjeBRUdOm8fQ+wsm9SstL7msoIjN8AwjHQzAdUv3lhN6uehmkcBlPYxrfzlsxsLqvBoGUKxWZswhYpi6hllMLx9ENgRd++l5K5V0D9AXQe2dge80iW3Y9KTjOsdQSsoFHFmZoUk3ZmIKcwrdcJasI7AN9/+jDcG7Wv8LaTKrcAzUEVJL6NIoU4/wDjMYoJIMODBIrqFYpXamDNeMuAfqyS1yItA+CcPldj2dkCvRmCYToprH/kdFXQgupDNz/HvNEo53BdKoo7W+hbqkKfvdxpolEYm3vnV4XXvw="
      distributions: "sdist bdist_wheel"
      on:
        tags: true
        branch: master
